grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 3
    verbose: 3
model_selection:
  module_0:
    class: CatBoostRegressor
    module: catboost
    params:
      iterations: 100
      learning_rate: 0.1
      depth: 6
      border_count: 128
    search_param_grid:
      iterations:
      - 100
      - 200
      - 300
      depth:
      - 4
      - 6
      learning_rate:
      - 0.1
      - 0.3
      - 0.5
      border_count:
      - 64
      - 128

      
  module_1:
    class: XGBRegressor
    module: xgboost
    params:
      learning_rate: 0.1
      max_depth: 4
      n_estimators: 300
    search_param_grid:
      max_depth:
      - 4
      - 15
      - 20
      max_features:
      - sqrt
      - log2
      n_estimators:
      - 100
      - 200
      - 300